[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "GeoMultiCorr"
version = "0.0.0"
authors = [
  { name="Diego Cusicanqui", email="diego.cusicanqui@univ-grenoble-alpes.fr"},
  { name="Thibaut Duvanel", email="thibaut.duvanel@unil.ch" },
]
description = "A python lib to study earth-surface displacements from optical images with Ames Stereo Pipeline"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
]

[tool.hatch.build.targets.wheel]
packages = ["geomulticorr"]